# Generated by Django 3.0.3 on 2020-02-06 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Car Color',
                'verbose_name_plural': 'Car Colors',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.Colors')),
            ],
            options={
                'verbose_name': 'List of Car',
                'verbose_name_plural': 'List of Cars',
                'ordering': ['-name'],
            },
        ),
    ]
